services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - db_data:/data/db
volumes:
  db_data:
